<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>9.5.0</Version>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>MudX.MudBlazor.Extension</PackageId>        
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>Nuget.png</PackageIcon>
        <Company>MudX</Company>
        <Authors>Versile and Contributors</Authors>
        <Copyright>Copyright 2025 MudX</Copyright>
        <PackageTags>Blazor, MudBlazor, Material, Material Design, Components, Blazor Components, Blazor Library, Extension</PackageTags>
        <Description>MudX extends MudBlazor and provides additional enhancements and new components.</Description>
        <PackageProjectUrl>https://mudx.org</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/MudXtra/MudX</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyMetadata Include="PackageId" Value="$(PackageId)" />        
    </ItemGroup>    
    
    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>

        <!-- https://github.com/dotnet/runtime/issues/95134 -->
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>    
    
    <!-- Define paths -->
    <PropertyGroup>
        <ProjectRoot>$(MSBuildProjectDirectory)</ProjectRoot>
        <GeneratorPath>$(ProjectRoot)\..\MudX.Generator\MudX.Generator.csproj</GeneratorPath>
        <MudXOutputPath>$(ProjectRoot)\wwwroot</MudXOutputPath>
        <StampsFilePath>$(MudXOutputPath)\modules\__stamp__.txt</StampsFilePath>
        <ScriptsDirectory>$(ProjectRoot)\Scripts</ScriptsDirectory>
        <Title>MudX Extensions for MudBlazor</Title>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="MudX.UnitTests;MudX.Docs" />
    </ItemGroup>
    
    <!-- Collect all .js files in Scripts directory with timestamps -->
    <ItemGroup>
        <ScriptFiles Include="$(ScriptsDirectory)\**\*.js;$(MudXOutputPath)\mudx.js;$(ScriptsDirectory)\**\*.css" />
        <StampsFile Include="$(StampsFilePath)" />
        <OutputFiles Include="$(MudXOutputPath)modules\**\*.js" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="..\..\images\Nuget.png">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="wwwroot\prism\prism.js" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="MudBlazor" Version="9.9.0" />
    </ItemGroup>
   
    <!-- Create item with filename and timestamp metadata -->
    <ItemGroup>
        <ScriptFilesWithTimestamps Include="@(ScriptFiles)">
            <FileInfo>%(Identity)|%(ModifiedTime)</FileInfo>
        </ScriptFilesWithTimestamps>
    </ItemGroup>

    <!-- This takes a list of ScriptFiles and compares it to the StampsFile timestamp. If any are newer it triggers a build -->
    <Target Name="GeneratorBeforeBuild" BeforeTargets="Build" Inputs="@(ScriptFiles)" Outputs="@(StampsFile)">
        <Message Importance="high" Text="======================================" />
        <Message Importance="high" Text="MudX.Generator: Starting MudX generation..." />

        <!-- Build and run in one command -->
        <Exec Command="dotnet run --project &quot;$(GeneratorPath)&quot; --configuration Release --framework $(TargetFramework) -- &quot;$(MudXOutputPath)&quot; &quot;$(ScriptsDirectory)&quot;" ConsoleToMSBuild="true" ContinueOnError="false" />

        <!--  Write timestamps to file -->
        <WriteLinesToFile File="$(StampsFilePath)" Lines="@(ScriptFilesWithTimestamps->'%(FileInfo)')" Overwrite="true" />

        <Message Importance="high" Text="MudX.Generator: Finished MudX generation..." />
        <Message Importance="high" Text="======================================" />
    </Target>
  
    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

</Project>
