name: '[OLD] Update MudX Version'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag to publish (e.g., v8.9.0)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    if: ${{ false }}
    name: Update Version
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version number
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Update Version in csproj
        run: |
          sed -i 's|\(<Version>\)[^<]*\(</Version>\)|\1${{ env.VERSION }}\2|' ./src/MudX/MudX.csproj

      - name: Verify csproj Version
        run: |
          actual=$(grep -oPm1 "(?<=<Version>)[^<]+" ./src/MudX/MudX.csproj)
          if [ "$actual" != "${VERSION}" ]; then
            echo "❌ Version not updated correctly in csproj (found: $actual, expected: $VERSION)"
            exit 1
          else
            echo "Version updated to $actual"
          fi

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version
          base: dev
          title: "[BOT] Update MudX Version to ${{ env.VERSION }}"
          body: |
            Automated update of MudX.csproj <Version> tag to ${{ env.VERSION }}
          commit-message: "Update MudX.csproj version to ${{ env.VERSION }}"
          delete-branch: true
          labels: automerge

      - name: Auto-approve PR
        if: steps.cpr.outputs.pull-request-number != ''
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          github-token: ${{ secrets.GH_BOT_TOKEN }}

      - id: automerge
        name: Auto-Merge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GH_BOT_TOKEN }}"
          PULL_REQUEST: ${{ steps.cpr.outputs.pull-request-number }}
          MERGE_DELETE_BRANCH: "TRUE"
          review-message: "Auto approved Automated PR"
